# Generated by Django 3.1 on 2020-09-09 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=20)),
                ('Last_Name', models.CharField(max_length=20)),
                ('Sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='Male', max_length=1)),
                ('Grade', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], default=1)),
                ('Nationality', models.CharField(default='Lebanese', max_length=20)),
                ('Born_in', models.IntegerField(default=1970)),
                ('Father', models.CharField(default='unknown', max_length=20)),
                ('Mother', models.CharField(default='unknown', max_length=20)),
                ('City', models.CharField(default='unknown', max_length=20)),
                ('Address', models.CharField(default='address', max_length=20)),
                ('Building', models.CharField(default='unknown', max_length=20)),
                ('Floor', models.CharField(default='unknown', max_length=20)),
                ('Fixed', models.IntegerField(default=0)),
                ('Mobile', models.IntegerField(default=0)),
                ('Medical_state', models.CharField(choices=[('H', 'Healthy'), ('NH', 'Sickboi')], default='Healthy', max_length=3)),
                ('Student_Bloodtype', models.CharField(choices=[('A', 'A+'), ('A', 'A-'), ('B', 'B+'), ('B', 'B-'), ('AB', 'AB+'), ('AB', 'AB-'), ('O', 'O+'), ('O', 'O-')], default='A+', max_length=3)),
                ('Guardian', models.CharField(choices=[('M', 'Mother'), ('F', 'Father')], default='Mother', max_length=1)),
                ('Guardian_Phone', models.IntegerField(default=0)),
                ('Guardian_Level_of_Education', models.CharField(default='unknown', max_length=20)),
                ('Guardian_City', models.CharField(default='unknown', max_length=20)),
                ('Guardian_Address', models.CharField(default='unknown', max_length=20)),
                ('Guardian_Building', models.CharField(default='unknown', max_length=20)),
                ('Guardian_Bloodtype', models.CharField(choices=[('A', 'A+'), ('A', 'A-'), ('B', 'B+'), ('B', 'B-'), ('AB', 'AB+'), ('AB', 'AB-'), ('O', 'O+'), ('O', 'O-')], default='A+', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=20)),
                ('Last_Name', models.CharField(max_length=20)),
                ('Subject', models.CharField(choices=[('E', 'English'), ('E', 'Arabic'), ('E', 'Math'), ('E', 'Physics'), ('E', 'Biology'), ('E', 'Chemistry'), ('E', 'History'), ('E', 'Geography'), ('E', 'Civics'), ('E', 'Religion'), ('E', 'PE')], max_length=1)),
                ('Sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('Nationality', models.CharField(max_length=20)),
                ('Born_in', models.IntegerField(default=1970)),
                ('City', models.CharField(max_length=20)),
                ('Address', models.CharField(max_length=20)),
                ('Building', models.CharField(max_length=20)),
                ('Floor', models.CharField(max_length=20)),
                ('Fixed', models.IntegerField(default=0)),
                ('Mobile', models.IntegerField(default=0)),
                ('Bloodtype', models.CharField(choices=[('A', 'A+'), ('A', 'A-'), ('B', 'B+'), ('B', 'B-'), ('AB', 'AB+'), ('AB', 'AB-'), ('O', 'O+'), ('O', 'O-')], max_length=3)),
            ],
        ),
    ]
